features:
  do_letterbox: false # Process only middle third of image.
  detection:
    min_grad_mag: 5.0 # Minimum gradient magntiude.
    min_error: 100.0 # Minimum photo error.
    win_size: 16 # Detection grid resolution (win_size x win_size).
  tracking:
    win_size: 5 # Feature tracking window size. If not using LK, must be odd.
    max_dropouts: 10 # Max number of missed detections before feature is killed.
    epipolar_line_var: 10.0 # Epipolar line noise variance.

regularization:
  do_median_filter: false # Apply median filter on graph.
  do_lowpass_filter: false # Apply lowpass filter on graph.
  do_nltgv2: true # Apply NLTGV2-L1 (i.e. planar) regularization.
  nltgv2:
    adaptive_data_weights: false # Set vertex data weights to inverse idepth variance.
    rescale_data: false # Rescale data to have mean 1.
    init_with_prediction: true # Initialize vertex idepths with predicted value from dense idepthmap.
    idepth_var_max: 0.01 # Maximum idepth var before feature can be added to graph.
    data_factor: 0.1 # Scalar that controls smoothness vs. data (0.1 for lvl5, 0.25 for lvl3).
    step_x: 0.001 # Optimization primal step size.
    step_q: 125.0 # Optimization dual step size.
    theta: 0.25 # Extra-gradient step size.
    min_height: -100000000000000.0 # Minimum height of features that are added to graph.
    max_height: 100000000000000.0 # Maximum height of features that are added to graph.
    check_sticky_obstacles: True
